// ─────────────────────────────────────────────────────────────────────────────
// EDMA Perfume — ERP TypeScript Types
// Mirrors the Supabase schema in 001_erp_schema.sql
// ─────────────────────────────────────────────────────────────────────────────

// ── Primitives ────────────────────────────────────────────────────────────────

export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
export type OrderSource = 'website' | 'whatsapp' | 'instagram';

// ── Row shapes (what Supabase returns on SELECT) ──────────────────────────────

export interface Product {
    id:                  string;
    name:                string;
    name_ar:             string;
    price:               number;
    stock_quantity:      number;
    low_stock_threshold: number;
    image_url:           string | null;
    created_at:          string;
}

export interface Customer {
    id:            string;
    name:          string;
    phone:         string | null;
    email:         string | null;
    city:          string | null;
    country:       string;
    total_orders:  number;
    total_spent:   number;
    created_at:    string;
}

export interface Order {
    id:            string;
    order_number:  string;
    customer_id:   string | null;
    product_id:    string | null;
    quantity:      number;
    total_amount:  number;
    status:        OrderStatus;
    source:        OrderSource;
    notes:         string | null;
    created_at:    string;
    updated_at:    string;
}

export interface InventoryLog {
    id:            string;
    product_id:    string | null;
    change_amount: number;
    reason:        string | null;
    created_at:    string;
}

// ── Insert shapes (id and created_at are generated by the DB) ─────────────────

export type ProductInsert = Omit<Product, 'id' | 'created_at'>;
export type CustomerInsert = Omit<Customer, 'id' | 'created_at'>;
export type OrderInsert = Omit<Order, 'id' | 'created_at' | 'updated_at'>;
export type InventoryLogInsert = Omit<InventoryLog, 'id' | 'created_at'>;

// ── Update shapes (all fields optional except the ones we never update) ───────

export type ProductUpdate   = Partial<ProductInsert>;
export type CustomerUpdate  = Partial<CustomerInsert>;
export type OrderUpdate     = Partial<Pick<Order, 'status' | 'notes' | 'quantity' | 'total_amount'>>;

// ── Joined / enriched shapes returned by complex queries ─────────────────────

/** Order row with customer name and product name pre-joined (for the orders table view) */
export interface OrderWithDetails extends Order {
    customer_name:    string | null;
    customer_phone:   string | null;
    product_name:     string | null;
    product_name_ar:  string | null;
}

/** Product with a derived low-stock flag (computed client-side) */
export interface ProductWithStockStatus extends Product {
    stock_status: 'ok' | 'low' | 'critical';
}

// ── Dashboard aggregate ───────────────────────────────────────────────────────

export interface DashboardMetrics {
    total_revenue:      number;  // sum of delivered order amounts
    total_orders:       number;  // count of all orders
    total_customers:    number;  // count of distinct customers
    pending_orders:     number;  // orders with status = pending | processing
    low_stock_count:    number;  // products at or below threshold
    revenue_this_month: number;
    orders_this_month:  number;
    top_product:        { name: string; units_sold: number } | null;
}
